{"name": "Авторизация с некорректным  ", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.test_login.TestLoginUser object at 0x10a91b500>, register_new_user_return_login_and_password = [], email = ' '\n\n    @allure.title('Авторизация с некорректным {email}')\n    @pytest.mark.parametrize('email', ['faker.email()', ' '], ids=['incorrect_email', 'empty_email'])\n    def test_login_user_incorrect_email_and_correct_password(self, register_new_user_return_login_and_password,\n                                                             email):\n        faker = Faker()\n        data = register_new_user_return_login_and_password\n        payload = {\n            \"email\": email,\n>           \"password\": data[1]\n        }\nE       IndexError: list index out of range\n\ntests/test_login.py:38: IndexError"}, "parameters": [{"name": "email", "value": "' '"}], "start": 1721241521322, "stop": 1721241521399, "uuid": "954c2428-3453-4000-b936-7a6e53a3181f", "historyId": "00e776b3746addf8effbde6864170250", "testCaseId": "7092bc473ffb96023fc9047acacdda00", "fullName": "tests.test_login.TestLoginUser#test_login_user_incorrect_email_and_correct_password", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "NB-ISC-14346"}, {"name": "thread", "value": "38742-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}