{"name": "Изменение данных для не авторизованного пользователя", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "self = <allure_commons._allure.fixture object at 0x1096d6330>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @pytest.fixture(scope='function')\n    def register_new_user_return_response():\n        with allure.step('Получение данных о зарегистрированном пользователе'):\n            data = api.create_new_user()\n    \n            yield data[1]\n    \n        with allure.step('Получение токена созданного пользователя'):\n>           access_token = data[1].json()[\"accessToken\"]\nE           KeyError: 'accessToken'\n\nconftest.py:21: KeyError"}, "parameters": [{"name": "changed_data", "value": "'{\"email\": fake.email(), \"password\": data[1],\"name\": data[2]}'"}], "start": 1721244620909, "stop": 1721244621223, "uuid": "15625563-6452-4452-ba07-00c48d648d6c", "historyId": "96de5e1600819154567b23cd0801023e", "testCaseId": "4dfaca9359ac1c438ac0b28494690521", "fullName": "tests.test_udate_user_data.TestUpdateUserData#test_update_info_non_authorized_user", "labels": [{"name": "suite", "value": "Изменение данных пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestUpdateUserData"}, {"name": "host", "value": "NB-ISC-14346"}, {"name": "thread", "value": "41162-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_udate_user_data"}]}