{"name": "Авторизация с некорректным  ", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <tests.test_login.TestLoginUser object at 0x1100139e0>, register_new_user_return_login_and_password = [], password = ' '\n\n    @allure.title('Авторизация с некорректным {password}')\n    @pytest.mark.parametrize('password', ['faker.password()', ' '], ids=['incorrect password', 'empty password'])\n    def test_login_user_correct_email_incorrect_password(self, register_new_user_return_login_and_password, password):\n        faker = Faker()\n        data = register_new_user_return_login_and_password\n        payload = {\n>           \"email\": data[0],\n            \"password\": password\n        }\nE       IndexError: list index out of range\n\ntests/test_login.py:50: IndexError"}, "parameters": [{"name": "password", "value": "' '"}], "start": 1721241070580, "stop": 1721241070666, "uuid": "5b0c4406-5083-4479-9f94-9a5469a8edcf", "historyId": "9c1dfd3d7ba5503d7da096ce0415e09e", "testCaseId": "f04dfc293f9635f75c5a3dcddcbba3a5", "fullName": "tests.test_login.TestLoginUser#test_login_user_correct_email_incorrect_password", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "NB-ISC-14346"}, {"name": "thread", "value": "38470-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}